name: Test label


on:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read
  actions: read

run-name: Test label

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const commit_sha = context.sha;
            
            const response =
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  owner,
                  repo,
                  commit_sha,
                });
            core.debug(`Retrieved commit data: ${response.data}`);
            
            const pr = response.data.length > 0 && response.data[0];
            core.debug(`Retrieved PR: ${pr}`);
            
            const labels = pr ? pr.labels.map((label) => label.name || "") : [];
            const labelsString = labels.join(' ');
            core.info(labelsString);
            core.setOutput('labels', labelsString);
      - name: Echo
        if: ${{ !contains(steps.pr-labels.outputs.labels, 'skip-e2e') }}
        run: echo "I ran"