name: Test label


on:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read
  actions: read

run-name: Test label

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo
        if: ${{ !contains(steps.pr-labels.outputs.labels, 'skip-e2e') }}
        run: echo "I ran"